Give existing Comrades a default-blank CoC field.
Otherwise, running the migration against an existing PostgreSQL database
gives this error:

django.db.utils.IntegrityError: column "agreed_to_code_of_conduct" contains null values

I think SQLite didn't enforce this constraint which is why the migration
didn't fail during local development?