Pin node and npm version to Debian 11 (bullseye) versions
I need to slowly update the server, and the dokku deployment is failing when it tries to pull in the default npm heroku package (npm 10.2.3).

The error is:

       npm ERR! cb.apply is not a function

See full logs below.

For now, I'm fixing it by pinning our node and npm versions to Debian old stable, which is currently Debian 11 (bullseye). That's the version I'm running on my Debian laptop. (Note: I really need to upgrade to Debian stable -- Debian 12, bookworm, but that's not happening today.)

sage@macbeth:~/outreachy/outreachyhome$ git push --no-verify dokku-test d9f6543fcd92f0ee6e0db0b04545e0ff2be2e854:master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 387 bytes | 387.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
-----> Setting config vars
       GIT_REV:  d9f6543fcd92f0ee6e0db0b04545e0ff2be2e854
-----> Cleaning up...
-----> Building test from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs python
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs#v202@v202
=====> Detected Framework: Node.js

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version 18.x...
       Downloading and installing node 18.19.0...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 10.2.3)...
       npm 5.10.0 installed

-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build

-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! cb.apply is not a function

       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.z41Pw/_logs/2023-12-05T19_53_21_847Z-debug.log

-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       Some possible problems:

       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       Love,
       Heroku

remote:  !     Failure during app build
remote:  !     Retagging old image c517c2dcf77f
remote: fa63a9d77223 as dokku/test:latest
remote:  !     App build failed
To outreachy.org:test
 ! [remote rejected]   d9f6543fcd92f0ee6e0db0b04545e0ff2be2e854 -> master (pre-receive hook declined)
error: failed to push some refs to 'outreachy.org:test'