Update dependencies - django pinned to 3.1.x, django-reversion pinned to 3.x
Summary
---

Update dependencies as much as we can. django-language-field has not
been updated to work with Django 3.2 (see details below).
django-reversion has a breaking change in 4.0.

django-language-field
---

We added field to represent the language interns and mentors speak. It
was a disaster, since loading the page with all the worlds' languages as
drop-down choices was very slow. So we later removed the field.

Now that field addition and deletion is in our migration history.
Whenever a new database is created (either locally or on a webserver),
Django goes through all migration files, and applies them one at a time.
That means when it gets to the old migration that adds the language
field, django-language-field needs to be installed or an error will get
thrown. Once the migration is done, the installed django-language-field
package is never used.

There is a way to "squash" migration history. It's a bit like
`git rebase -i`, where you can squash multiple commits into one commit.
Django takes the series of migrations that are being squashed, and
it creates one migration that represents the results of the database
operations those series of migrations does.

Once we "squash" the migration that adds the LanguageField field to the
database into the migration that removes that field from the database,
the result will be as if that field never existed at all. Basically that
migration would be recorded as a "noop" -- nothing in the database
changed.

Therefore, until we squash our migration history, the
django-language-field package will have to remain installed.

I got the following error below. Searching around for the error message
lead me to this stackoverflow post:

https://stackoverflow.com/questions/66981658/django-3-2-attributeerror-textfield-object-has-no-attribute-db-collation

Based on that post, it seems like django-language-field would need to be
patched to pass db_collate=None as a variable in the custom model's
__init__ function.

Here is the error I got when I tried to update to Django 3.2:

Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/home/sage/outreachy/outreachyhome/./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/commands/test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/test/runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/test/runner.py", line 643, in setup_databases
    return _setup_databases(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/test/utils.py", line 179, in setup_databases
    connection.creation.create_test_db(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/backends/base/creation.py", line 74, in create_test_db
    call_command(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/migration.py", line 116, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 80, in state_forwards
    state.add_model(ModelState(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 95, in add_model
    self.reload_model(app_label, model_name)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 156, in reload_model
    self._reload(related_models)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 189, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 305, in render_multiple
    model.render(self)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 565, in render
    body = {name: field.clone() for name, field in self.fields.items()}
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/migrations/state.py", line 565, in <dictcomp>
    body = {name: field.clone() for name, field in self.fields.items()}
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 512, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct
    if self.db_collation:
AttributeError: 'LanguageField' object has no attribute 'db_collation'

django-reversion
---

Here's the error I got when updating to django-reversion 4.0.0:

$ ./manage.py migrate
Traceback (most recent call last):
  File "/home/sage/outreachy/outreachyhome/./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sage/.local/share/virtualenvs/outreachyhome-U2aKqKTe/lib/python3.9/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/sage/outreachy/outreachyhome/outreachyhome/urls.py", line 9, in <module>
    from home import urls as home_urls
  File "/home/sage/outreachy/outreachyhome/home/urls.py", line 1, in <module>
    from . import dashboard, views
  File "/home/sage/outreachy/outreachyhome/home/dashboard.py", line 41, in <module>
    from .mixins import ComradeRequiredMixin
  File "/home/sage/outreachy/outreachyhome/home/mixins.py", line 75, in <module>
    class ApprovalStatusAction(LoginRequiredMixin, ComradeRequiredMixin, reversion.views.RevisionMixin, UpdateView):
AttributeError: module 'reversion' has no attribute 'views'

I didn't debug this error at all, but I do note the django-reversion
change log has a note that 4.0.0 has a breaking change:

https://django-reversion.readthedocs.io/en/stable/changelog.html#id1

Pin django-reversion to a 3.x version until we can investigate views
that use django-reversion.